 /* MySQL-Front 3.2  (Build 4.15)*/
/*/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT ;*/
/*/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS ;*/
/*/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION ;*/
/*/*!40101 SET CHARACTER SET 'latin1' ;*/

/* Host: ps0154    Database: csm_catissuecore */
/* ------------------------------------------------------*/
/* Server version 4.1.10-nt*/

/*USE `catissuecore`; */

SET NAMES utf8;
SET storage_engine=InnoDB;
SET SQL_MODE='';

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

/* Table Objects for table csm_application */

DROP TABLE IF EXISTS `CSM_APPLICATION`;

CREATE TABLE `CSM_APPLICATION` (
  `APPLICATION_ID` bigint(20) NOT NULL auto_increment,
  `APPLICATION_NAME` varchar(255) NOT NULL default '',
  `APPLICATION_DESCRIPTION` varchar(200) NOT NULL default '',
  `DECLARATIVE_FLAG` tinyint(1) default NULL,
  `ACTIVE_FLAG` tinyint(1) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '0000-00-00',
  `DATABASE_URL` varchar(100) default NULL,
  `DATABASE_USER_NAME` varchar(100) default NULL,
  `DATABASE_PASSWORD` varchar(100) default NULL,
  `DATABASE_DIALECT` varchar(100) default NULL,
  `DATABASE_DRIVER` varchar(100) default NULL,
  PRIMARY KEY  (`APPLICATION_ID`),
  UNIQUE KEY `UQ_APPLICATION_NAME` (`APPLICATION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_application*/

INSERT INTO `CSM_APPLICATION` (`APPLICATION_ID`,`APPLICATION_NAME`,`APPLICATION_DESCRIPTION`,`DECLARATIVE_FLAG`,`ACTIVE_FLAG`,`UPDATE_DATE`,`DATABASE_URL`,`DATABASE_USER_NAME`,`DATABASE_PASSWORD`,`DATABASE_DIALECT`,`DATABASE_DRIVER`) values (1,'query','AdvancedQuery',0,0,'2005-08-22',NULL,NULL,NULL,NULL,NULL);


/* Table Objects for table csm_group*/


DROP TABLE IF EXISTS `CSM_GROUP`;

CREATE TABLE `CSM_GROUP` (
  `GROUP_ID` bigint(20) NOT NULL auto_increment,
  `GROUP_NAME` varchar(255) NOT NULL default '',
  `GROUP_DESC` varchar(200) default NULL,
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  `APPLICATION_ID` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`GROUP_ID`),
  UNIQUE KEY `UQ_GROUP_GROUP_NAME` (`APPLICATION_ID`,`GROUP_NAME`),
  KEY `idx_APPLICATION_ID` (`APPLICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_group*/


INSERT INTO `CSM_GROUP` (`GROUP_ID`,`GROUP_NAME`,`GROUP_DESC`,`UPDATE_DATE`,`APPLICATION_ID`) VALUES (1,'ADMINISTRATOR_GROUP','Group of Administrators','0000-00-00',1);


/* Table Objects for table csm_pg_pe*/


DROP TABLE IF EXISTS `CSM_PG_PE`;

CREATE TABLE `CSM_PG_PE` (
  `PG_PE_ID` bigint(20) NOT NULL auto_increment,
  `PROTECTION_GROUP_ID` bigint(20) NOT NULL default '0',
  `PROTECTION_ELEMENT_ID` bigint(20) NOT NULL default '0',
  `UPDATE_DATE` date default NULL,
  PRIMARY KEY  (`PG_PE_ID`),
  UNIQUE KEY `UQ_PROTECTION_GROUP_PROTECTION_ELEMENT_PROTECTION_GROUP_ID` (`PROTECTION_ELEMENT_ID`,`PROTECTION_GROUP_ID`),
  KEY `idx_PROTECTION_ELEMENT_ID` (`PROTECTION_ELEMENT_ID`),
  KEY `idx_PROTECTION_GROUP_ID` (`PROTECTION_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_pg_pe*/


/* Table Objects for table csm_privilege*/



DROP TABLE IF EXISTS `CSM_PRIVILEGE`;

CREATE TABLE `CSM_PRIVILEGE` (
  `PRIVILEGE_ID` bigint(20) NOT NULL auto_increment,
  `PRIVILEGE_NAME` varchar(100) NOT NULL default '',
  `PRIVILEGE_DESCRIPTION` varchar(200) default NULL,
  `UPDATE_DATE` date NOT NULL default '0000-00-00',
  PRIMARY KEY  (`PRIVILEGE_ID`),
  UNIQUE KEY `UQ_PRIVILEGE_NAME` (`PRIVILEGE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_privilege*/



INSERT INTO `CSM_PRIVILEGE` (`PRIVILEGE_ID`,`PRIVILEGE_NAME`,`PRIVILEGE_DESCRIPTION`,`UPDATE_DATE`) VALUES (1,'EXECUTE_MANAGED_QUERY','This privilege grants permission to a user to create an entity. This entity can be an object, a database entry, or a resource such as a network connection','2005-08-22');

/* Table Objects for table csm_protection_element*/



DROP TABLE IF EXISTS `CSM_PROTECTION_ELEMENT`;

CREATE TABLE `CSM_PROTECTION_ELEMENT` (
  `PROTECTION_ELEMENT_ID` bigint(20) NOT NULL auto_increment,
  `PROTECTION_ELEMENT_NAME` varchar(100) NOT NULL default '',
  `PROTECTION_ELEMENT_DESCRIPTION` varchar(200) default NULL,
  `OBJECT_ID` varchar(100) NOT NULL default '',
  `ATTRIBUTE` varchar(100) default NULL,
  `PROTECTION_ELEMENT_TYPE` varchar(100) default NULL,
  `APPLICATION_ID` bigint(20) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  PRIMARY KEY  (`PROTECTION_ELEMENT_ID`),
  UNIQUE KEY `UQ_PE_PE_NAME_ATTRIBUTE_APP_ID` (`OBJECT_ID`,`ATTRIBUTE`,`APPLICATION_ID`),
  UNIQUE KEY `UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID` (`PROTECTION_ELEMENT_NAME`,`ATTRIBUTE`,`APPLICATION_ID`),
  KEY `idx_APPLICATION_ID` (`APPLICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/* Dumping data for table csm_protection_element*/


DROP TABLE IF EXISTS `CSM_PROTECTION_GROUP`;

CREATE TABLE `CSM_PROTECTION_GROUP` (
  `PROTECTION_GROUP_ID` bigint(20) NOT NULL auto_increment,
  `PROTECTION_GROUP_NAME` varchar(100) NOT NULL default '',
  `PROTECTION_GROUP_DESCRIPTION` varchar(200) default NULL,
  `APPLICATION_ID` bigint(20) NOT NULL default '0',
  `LARGE_ELEMENT_COUNT_FLAG` tinyint(1) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  `PARENT_PROTECTION_GROUP_ID` bigint(20) default NULL,
  PRIMARY KEY  (`PROTECTION_GROUP_ID`),
  UNIQUE KEY `UQ_PROTECTION_GROUP_PROTECTION_GROUP_NAME` (`APPLICATION_ID`,`PROTECTION_GROUP_NAME`),
  KEY `idx_APPLICATION_ID` (`APPLICATION_ID`),
  KEY `idx_PARENT_PROTECTION_GROUP_ID` (`PARENT_PROTECTION_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_protection_group*/



INSERT INTO `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`,`PROTECTION_GROUP_NAME`,`PROTECTION_GROUP_DESCRIPTION`,`APPLICATION_ID`,`LARGE_ELEMENT_COUNT_FLAG`,`UPDATE_DATE`,`PARENT_PROTECTION_GROUP_ID`) 
		VALUES (1,'ADMINISTRATOR_PROTECTION_GROUP','Protection elements for class names of objects that belong to Administrative data',1,0,'0000-00-00',NULL);
INSERT INTO `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`,`PROTECTION_GROUP_NAME`,`PROTECTION_GROUP_DESCRIPTION`,`APPLICATION_ID`,`LARGE_ELEMENT_COUNT_FLAG`,`UPDATE_DATE`,`PARENT_PROTECTION_GROUP_ID`) VALUES (2,'Public_Query_Protection_Group','Shared Query Protection Group',1,0,'0000-00-00',NULL);



/* Table Objects for table csm_role*/



DROP TABLE IF EXISTS `CSM_ROLE`;

CREATE TABLE `CSM_ROLE` (
  `ROLE_ID` bigint(20) NOT NULL auto_increment,
  `ROLE_NAME` varchar(100) NOT NULL default '',
  `ROLE_DESCRIPTION` varchar(200) default NULL,
  `APPLICATION_ID` bigint(20) NOT NULL default '0',
  `ACTIVE_FLAG` tinyint(1) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  PRIMARY KEY  (`ROLE_ID`),
  UNIQUE KEY `UQ_ROLE_ROLE_NAME` (`APPLICATION_ID`,`ROLE_NAME`),
  KEY `idx_APPLICATION_ID` (`APPLICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_role*/



INSERT INTO `CSM_ROLE` (`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`APPLICATION_ID`,`ACTIVE_FLAG`,`UPDATE_DATE`) VALUES (1,'Administrator','Role for Administrator',1,0,'0000-00-00');
INSERT INTO `CSM_ROLE` (`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`APPLICATION_ID`,`ACTIVE_FLAG`,`UPDATE_DATE`) VALUES (2,'EXECUTE_QUERY','Role for Supervisor',1,0,'0000-00-00');


/* Table Objects for table csm_role_privilege*/



DROP TABLE IF EXISTS `CSM_ROLE_PRIVILEGE`;

CREATE TABLE `CSM_ROLE_PRIVILEGE` (
  `ROLE_PRIVILEGE_ID` bigint(20) NOT NULL auto_increment,
  `ROLE_ID` bigint(20) NOT NULL default '0',
  `PRIVILEGE_ID` bigint(20) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  PRIMARY KEY  (`ROLE_PRIVILEGE_ID`),
  UNIQUE KEY `UQ_ROLE_PRIVILEGE_ROLE_ID` (`PRIVILEGE_ID`,`ROLE_ID`),
  KEY `idx_PRIVILEGE_ID` (`PRIVILEGE_ID`),
  KEY `idx_ROLE_ID` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_role_privilege*/



INSERT INTO `CSM_ROLE_PRIVILEGE` (`ROLE_PRIVILEGE_ID`,`ROLE_ID`,`PRIVILEGE_ID`,`UPDATE_DATE`) VALUES (1,1,1,'0000-00-00');
INSERT INTO `CSM_ROLE_PRIVILEGE` (`ROLE_PRIVILEGE_ID`,`ROLE_ID`,`PRIVILEGE_ID`,`UPDATE_DATE`) VALUES (2,2,1,'0000-00-00');



/* Table Objects for table csm_user*/



DROP TABLE IF EXISTS `CSM_USER`;

CREATE TABLE `CSM_USER` (
  `USER_ID` bigint(20) NOT NULL auto_increment,
  `LOGIN_NAME` varchar(100) NOT NULL default '',
  `FIRST_NAME` varchar(100) NOT NULL default '',
  `LAST_NAME` varchar(100) NOT NULL default '',
  `ORGANIZATION` varchar(100) default NULL,
  `DEPARTMENT` varchar(100) default NULL,
  `TITLE` varchar(100) default NULL,
  `PHONE_NUMBER` varchar(15) default NULL,
  `PASSWORD` varchar(100) default NULL,
  `EMAIL_ID` varchar(100) default NULL,
  `START_DATE` date default NULL,
  `END_DATE` date default NULL,
  `UPDATE_DATE` date NOT NULL default '0000-00-00',
  PRIMARY KEY  (`USER_ID`),
  UNIQUE KEY `UQ_LOGIN_NAME` (`LOGIN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_user*/



INSERT INTO `CSM_USER` (`USER_ID`,`LOGIN_NAME`,`FIRST_NAME`,`LAST_NAME`,`ORGANIZATION`,`DEPARTMENT`,`TITLE`,`PHONE_NUMBER`,`PASSWORD`,`EMAIL_ID`,`START_DATE`,`END_DATE`,`UPDATE_DATE`) VALUES (1,'admin@admin.com','Admin','Admin',NULL,NULL,NULL,NULL,'6c416f576765696c6e63316f326d3365','admin@admin.com','2005-08-30',NULL,'2005-08-30');


/* Table Objects for table csm_user_group*/



DROP TABLE IF EXISTS `CSM_USER_GROUP`;

CREATE TABLE `CSM_USER_GROUP` (
  `USER_GROUP_ID` bigint(20) NOT NULL auto_increment,
  `USER_ID` bigint(20) NOT NULL default '0',
  `GROUP_ID` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`USER_GROUP_ID`),
  KEY `idx_USER_ID` (`USER_ID`),
  KEY `idx_GROUP_ID` (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_user_group*/



INSERT INTO `CSM_USER_GROUP` (`USER_GROUP_ID`,`USER_ID`,`GROUP_ID`) VALUES (1,1,1);


/* Table Objects for table csm_user_group_role_pg*/



DROP TABLE IF EXISTS `CSM_USER_GROUP_ROLE_PG`;

CREATE TABLE `CSM_USER_GROUP_ROLE_PG` (
  `USER_GROUP_ROLE_PG_ID` bigint(20) NOT NULL auto_increment,
  `USER_ID` bigint(20) default NULL,
  `GROUP_ID` bigint(20) default NULL,
  `ROLE_ID` bigint(20) NOT NULL default '0',
  `PROTECTION_GROUP_ID` bigint(20) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '2005-01-01',
  PRIMARY KEY  (`USER_GROUP_ROLE_PG_ID`),
  KEY `idx_GROUP_ID` (`GROUP_ID`),
  KEY `idx_ROLE_ID` (`ROLE_ID`),
  KEY `idx_PROTECTION_GROUP_ID` (`PROTECTION_GROUP_ID`),
  KEY `idx_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_user_group_role_pg*/




/* Table Objects for table csm_user_pe*/



DROP TABLE IF EXISTS `CSM_USER_PE`;

CREATE TABLE `CSM_USER_PE` (
  `USER_PROTECTION_ELEMENT_ID` bigint(20) NOT NULL auto_increment,
  `PROTECTION_ELEMENT_ID` bigint(20) NOT NULL default '0',
  `USER_ID` bigint(20) NOT NULL default '0',
  `UPDATE_DATE` date NOT NULL default '0000-00-00',
  PRIMARY KEY  (`USER_PROTECTION_ELEMENT_ID`),
  UNIQUE KEY `UQ_USER_PROTECTION_ELEMENT_PROTECTION_ELEMENT_ID` (`USER_ID`,`PROTECTION_ELEMENT_ID`),
  KEY `idx_USER_ID` (`USER_ID`),
  KEY `idx_PROTECTION_ELEMENT_ID` (`PROTECTION_ELEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


/* Dumping data for table csm_user_pe*/





/*  Foreign keys for table csm_group*/



ALTER TABLE `CSM_GROUP`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_pg_pe*/



ALTER TABLE `CSM_PG_PE`
  ADD FOREIGN KEY (`PROTECTION_ELEMENT_ID`) REFERENCES `CSM_PROTECTION_ELEMENT` (`PROTECTION_ELEMENT_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_protection_element*/



ALTER TABLE `CSM_PROTECTION_ELEMENT`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_protection_group*/



ALTER TABLE `CSM_PROTECTION_GROUP`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PARENT_PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`);



/*  Foreign keys for table csm_role*/



ALTER TABLE `CSM_ROLE`
  ADD FOREIGN KEY (`APPLICATION_ID`) REFERENCES `CSM_APPLICATION` (`APPLICATION_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_role_privilege */



ALTER TABLE `CSM_ROLE_PRIVILEGE`
  ADD FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `CSM_PRIVILEGE` (`PRIVILEGE_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`ROLE_ID`) REFERENCES `CSM_ROLE` (`ROLE_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_user_group */



ALTER TABLE `CSM_USER_GROUP`
  ADD FOREIGN KEY (`GROUP_ID`) REFERENCES `CSM_GROUP` (`GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_user_group_role_pg */



ALTER TABLE `CSM_USER_GROUP_ROLE_PG`
  ADD FOREIGN KEY (`GROUP_ID`) REFERENCES `CSM_GROUP` (`GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_GROUP_ID`) REFERENCES `CSM_PROTECTION_GROUP` (`PROTECTION_GROUP_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`ROLE_ID`) REFERENCES `CSM_ROLE` (`ROLE_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE;



/*  Foreign keys for table csm_user_pe */



ALTER TABLE `CSM_USER_PE`
  ADD FOREIGN KEY (`USER_ID`) REFERENCES `CSM_USER` (`USER_ID`) ON DELETE CASCADE,
  ADD FOREIGN KEY (`PROTECTION_ELEMENT_ID`) REFERENCES `CSM_PROTECTION_ELEMENT` (`PROTECTION_ELEMENT_ID`) ON DELETE CASCADE;


/*/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT ;*/
/*/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS ;*/
/*/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION ;*/

