SET storage_engine=InnoDB;
SET FOREIGN_KEY_CHECKS=0;
drop table if exists CATISSUE_AUDIT_EVENT_QUERY_LOG;
drop table if exists CATISSUE_AUDIT_EVENT;
drop table if exists CATISSUE_AUDIT_EVENT_LOG;
drop table if exists CATISSUE_AUDIT_EVENT_DETAILS;
drop table if exists CATISSUE_SPECIMEN_LABEL_COUNT;
drop table if exists CATISSUE_USER;

drop table if exists CATISSUE_ADDRESS;
drop table if exists CATISSUE_INSTITUTION;
drop table if exists CATISSUE_DEPARTMENT;
drop table if exists CATISSUE_CANCER_RESEARCH_GROUP;
drop table if exists  CATISSUE_PASSWORD;

SET FOREIGN_KEY_CHECKS=1;

create table CATISSUE_AUDIT_EVENT_QUERY_LOG (
   IDENTIFIER bigint not null auto_increment,
   QUERY_DETAILS longtext,  
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);



create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER bigint not null auto_increment,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP datetime,
   USER_ID bigint,
   COMMENTS text,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER bigint not null auto_increment,
   OBJECT_IDENTIFIER bigint,
   OBJECT_NAME varchar(50),
   EVENT_TYPE varchar(50),
   AUDIT_EVENT_ID bigint,
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER bigint not null auto_increment,
   ELEMENT_NAME varchar(150),
   PREVIOUS_VALUE varchar(150),
   CURRENT_VALUE varchar(500),
   AUDIT_EVENT_LOG_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_USER (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   EMAIL_ADDRESS VARCHAR(100),
   FIRST_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50),
   LOGIN_NAME VARCHAR(50) not null unique,
   START_DATE DATE,
   ACTIVITY_STATUS VARCHAR(50),
   DEPARTMENT_ID BIGINT,
   CANCER_RESEARCH_GROUP_ID BIGINT,
   INSTITUTION_ID BIGINT,
   ADDRESS_ID BIGINT,
   CSM_USER_ID BIGINT,
   STATUS_COMMENT TEXT,
   primary key (IDENTIFIER)
);

create table CATISSUE_ADDRESS (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   STREET VARCHAR(50),
   CITY VARCHAR(50),
   STATE VARCHAR(50),
   COUNTRY VARCHAR(50),
   ZIPCODE VARCHAR(30),
   PHONE_NUMBER VARCHAR(50),
   FAX_NUMBER VARCHAR(50),
   primary key (IDENTIFIER)
);
create table CATISSUE_INSTITUTION (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_DEPARTMENT (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) not null unique,
   primary key (IDENTIFIER)
);
create table CATISSUE_CANCER_RESEARCH_GROUP (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) not null unique,
   primary key (IDENTIFIER)
);

create table CATISSUE_PASSWORD (
   IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
   PASSWORD VARCHAR(50),
   UPDATE_DATE DATE,
   USER_ID BIGINT,
   primary key (IDENTIFIER)
);

alter table CATISSUE_AUDIT_EVENT_QUERY_LOG add index FK62DC439DBC7298A9 (AUDIT_EVENT_ID), add constraint FK62DC439DBC7298A9 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT add index FKACAF697A2206F20F (USER_ID), add constraint FKACAF697A2206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_LOG add index FK8BB672DF77F0B904 (AUDIT_EVENT_ID), add constraint FK8BB672DF77F0B904 foreign key (AUDIT_EVENT_ID) references CATISSUE_AUDIT_EVENT (IDENTIFIER);
alter table CATISSUE_AUDIT_EVENT_DETAILS add index FK5C07745D34FFD77F (AUDIT_EVENT_LOG_ID), add constraint FK5C07745D34FFD77F foreign key (AUDIT_EVENT_LOG_ID) references CATISSUE_AUDIT_EVENT_LOG (IDENTIFIER);

alter table CATISSUE_USER add index (INSTITUTION_ID), add constraint FKB025CFC71792AD22 foreign key (INSTITUTION_ID) references CATISSUE_INSTITUTION (IDENTIFIER);
alter table CATISSUE_USER add index (CANCER_RESEARCH_GROUP_ID), add constraint FKB025CFC7FFA96920 foreign key (CANCER_RESEARCH_GROUP_ID) references CATISSUE_CANCER_RESEARCH_GROUP (IDENTIFIER);
alter table CATISSUE_USER add index (ADDRESS_ID), add constraint FKB025CFC76CD94566 foreign key (ADDRESS_ID) references CATISSUE_ADDRESS (IDENTIFIER);
alter table CATISSUE_USER add index (DEPARTMENT_ID), add constraint FKB025CFC7F30C2528 foreign key (DEPARTMENT_ID) references CATISSUE_DEPARTMENT (IDENTIFIER);


