DROP TABLE CSM_APPLICATION;


CREATE TABLE CSM_APPLICATION (
  APPLICATION_ID DECIMAL(31) NOT NULL,
  APPLICATION_NAME varchar(255) NOT NULL default '',
  APPLICATION_DESCRIPTION varchar(200) NOT NULL default '',
  DECLARATIVE_FLAG DECIMAL(1,0) default NULL,
  ACTIVE_FLAG DECIMAL(1,0) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default current date,
  DATABASE_URL varchar(100) default NULL,
  DATABASE_USER_NAME varchar(100) default NULL,
  DATABASE_PASSWORD varchar(100) default NULL,
  DATABASE_DIALECT varchar(100) default NULL,
  DATABASE_DRIVER varchar(100) default NULL,
  PRIMARY KEY  (APPLICATION_ID),
  CONSTRAINT UQ_APPLICATION_NAME UNIQUE  (APPLICATION_NAME) 
);


/* Dumping data for table csm_application*/

INSERT INTO CSM_APPLICATION (APPLICATION_ID,APPLICATION_NAME,APPLICATION_DESCRIPTION,DECLARATIVE_FLAG,ACTIVE_FLAG,UPDATE_DATE,DATABASE_URL,DATABASE_USER_NAME,DATABASE_PASSWORD,DATABASE_DIALECT,DATABASE_DRIVER) values (1,'query','AdvancedQuery',0,0,CURRENT DATE,NULL,NULL,NULL,NULL,NULL);

/* Table Objects for table csm_group*/


DROP TABLE CSM_GROUP;


CREATE TABLE CSM_GROUP (
  GROUP_ID DECIMAL(31) NOT NULL,
  GROUP_NAME varchar(255) NOT NULL default '',
  GROUP_DESC varchar(200) default NULL,
  UPDATE_DATE date NOT NULL default '2005-01-01',
  APPLICATION_ID DECIMAL(31) NOT NULL default 0,
  PRIMARY KEY  (GROUP_ID),
  CONSTRAINT UQ_GROUP_GROUP_NAME UNIQUE (APPLICATION_ID,GROUP_NAME)
);
CREATE INDEX IDX_APPLICATION_ID ON CSM_GROUP(APPLICATION_ID);

/* Dumping data for table csm_group*/
/* Default date CURRENT DATE is replaced by CURRENT DATE */

INSERT INTO CSM_GROUP (GROUP_ID,GROUP_NAME,GROUP_DESC,UPDATE_DATE,APPLICATION_ID) VALUES (1,'ADMINISTRATOR_GROUP','Group of Administrators',CURRENT DATE,1);


/* Table Objects for table csm_pg_pe*/


DROP TABLE  CSM_PG_PE;

CREATE TABLE CSM_PG_PE (
  PG_PE_ID DECIMAL(31) NOT NULL ,
  PROTECTION_GROUP_ID DECIMAL(31) NOT NULL default 0,
  PROTECTION_ELEMENT_ID DECIMAL(31) NOT NULL default 0,
  UPDATE_DATE date default NULL,
  PRIMARY KEY  (PG_PE_ID),
  CONSTRAINT  UQ_PROTECTION_GROUP_PROTECTION_ELEMENT_PROTECTION_GROUP_ID UNIQUE (PROTECTION_ELEMENT_ID,PROTECTION_GROUP_ID)
) ;
CREATE INDEX IDX_PROTECTION_ELEMENT_ID ON CSM_PG_PE(PROTECTION_ELEMENT_ID);
CREATE INDEX IDX_PROTECTION_GROUP_ID ON CSM_PG_PE(PROTECTION_GROUP_ID);

/* Dumping data for table csm_pg_pe*/


/* Table Objects for table csm_privilege*/



DROP TABLE  CSM_PRIVILEGE;

CREATE TABLE CSM_PRIVILEGE (
  PRIVILEGE_ID DECIMAL(31) NOT NULL ,
  PRIVILEGE_NAME varchar(100) NOT NULL default '',
  PRIVILEGE_DESCRIPTION varchar(200) default NULL,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (PRIVILEGE_ID),
  CONSTRAINT UQ_PRIVILEGE_NAME UNIQUE (PRIVILEGE_NAME)
) ;


/* Dumping data for table csm_privilege*/



INSERT INTO CSM_PRIVILEGE (PRIVILEGE_ID,PRIVILEGE_NAME,PRIVILEGE_DESCRIPTION,UPDATE_DATE) VALUES (1,'EXECUTE_MANAGED_QUERY', 'THIS PRIVILEGE GRANTS PERMISSION TO A USER TO EXECUTE QUERY',CURRENT DATE);

/* Table Objects for table csm_protection_element*/



DROP TABLE  CSM_PROTECTION_ELEMENT;

CREATE TABLE CSM_PROTECTION_ELEMENT (
  PROTECTION_ELEMENT_ID DECIMAL(31) NOT NULL ,
  PROTECTION_ELEMENT_NAME varchar(100) NOT NULL default '',
  PROTECTION_ELEMENT_DESCRIPTION varchar(200) default NULL,
  OBJECT_ID varchar(100) NOT NULL default '',
  ATTRIBUTE varchar(100) not null default '',
  PROTECTION_ELEMENT_TYPE varchar(100) default NULL,
  APPLICATION_ID DECIMAL(31) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default '2005-01-01',
  PRIMARY KEY  (PROTECTION_ELEMENT_ID),
  CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_APP_ID UNIQUE (OBJECT_ID,ATTRIBUTE,APPLICATION_ID),
  CONSTRAINT UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID UNIQUE (PROTECTION_ELEMENT_NAME,ATTRIBUTE,APPLICATION_ID)
) ;
CREATE INDEX IDX_APPLICATION_ID ON CSM_PROTECTION_ELEMENT(APPLICATION_ID);


/* Dumping data for table csm_protection_element*/


/* Table Objects for table csm_protection_group*/


DROP TABLE  CSM_PROTECTION_GROUP;

CREATE TABLE CSM_PROTECTION_GROUP (
  PROTECTION_GROUP_ID DECIMAL(31) NOT NULL ,
  PROTECTION_GROUP_NAME varchar(100) NOT NULL default '',
  PROTECTION_GROUP_DESCRIPTION varchar(200) default NULL,
  APPLICATION_ID DECIMAL(31) NOT NULL default 0,
  LARGE_ELEMENT_COUNT_FLAG DECIMAL(1,0) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PARENT_PROTECTION_GROUP_ID DECIMAL(31) default NULL,
  PRIMARY KEY  (PROTECTION_GROUP_ID),
  CONSTRAINT UQ_PROTECTION_GROUP_PROTECTION_GROUP_NAME UNIQUE (APPLICATION_ID,PROTECTION_GROUP_NAME)
) ;
CREATE INDEX IDX_APPLICATION_ID ON CSM_PROTECTION_GROUP(APPLICATION_ID);
CREATE INDEX IDX_PARENT_PROTECTION_GROUP_ID ON CSM_PROTECTION_GROUP(PARENT_PROTECTION_GROUP_ID);

/* Dumping data for table csm_protection_group*/



INSERT INTO CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID,PROTECTION_GROUP_NAME,PROTECTION_GROUP_DESCRIPTION,APPLICATION_ID,LARGE_ELEMENT_COUNT_FLAG,UPDATE_DATE,PARENT_PROTECTION_GROUP_ID) 
		VALUES (1,'ADMINISTRATOR_PROTECTION_GROUP','Protection elements for class names of objects that belong to Administrative data',1,0,CURRENT DATE,NULL);
INSERT INTO CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID,PROTECTION_GROUP_NAME,PROTECTION_GROUP_DESCRIPTION,APPLICATION_ID,LARGE_ELEMENT_COUNT_FLAG,UPDATE_DATE,PARENT_PROTECTION_GROUP_ID) VALUES (2,'Public_Query_protection_Group',NULL,1,0,CURRENT DATE,NULL);



/* Table Objects for table csm_role*/



DROP TABLE  CSM_ROLE;

CREATE TABLE CSM_ROLE (
  ROLE_ID DECIMAL(31) NOT NULL ,
  ROLE_NAME varchar(100) NOT NULL default '',
  ROLE_DESCRIPTION varchar(200) default NULL,
  APPLICATION_ID DECIMAL(31) NOT NULL default 0,
  ACTIVE_FLAG DECIMAL(1,0) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (ROLE_ID),
  CONSTRAINT UQ_ROLE_ROLE_NAME UNIQUE (APPLICATION_ID,ROLE_NAME)
) ;
CREATE INDEX IDX_APPLICATION_ID ON CSM_ROLE(APPLICATION_ID);


/* Dumping data for table csm_role*/



INSERT INTO CSM_ROLE (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,APPLICATION_ID,ACTIVE_FLAG,UPDATE_DATE) VALUES (1,'Administrator','Role for Administrator',1,0,CURRENT DATE);
INSERT INTO CSM_ROLE (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,APPLICATION_ID,ACTIVE_FLAG,UPDATE_DATE) VALUES (2, 'EXECUTE_QUERY', 'EXECUTE_QUERY', 1, 0,CURRENT DATE);

/* Table Objects for table csm_role_privilege*/



DROP TABLE  CSM_ROLE_PRIVILEGE;

CREATE TABLE CSM_ROLE_PRIVILEGE (
  ROLE_PRIVILEGE_ID DECIMAL(31) NOT NULL ,
  ROLE_ID DECIMAL(31) NOT NULL default 0,
  PRIVILEGE_ID DECIMAL(31) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (ROLE_PRIVILEGE_ID),
  CONSTRAINT UQ_ROLE_PRIVILEGE_ROLE_ID UNIQUE (PRIVILEGE_ID,ROLE_ID)
) ;
CREATE INDEX IDX_PRIVILEGE_ID ON CSM_ROLE_PRIVILEGE(PRIVILEGE_ID);
CREATE INDEX IDX_ROLE_ID ON CSM_ROLE_PRIVILEGE(ROLE_ID);


/* Dumping data for table csm_role_privilege*/



INSERT INTO CSM_ROLE_PRIVILEGE (ROLE_PRIVILEGE_ID,ROLE_ID,PRIVILEGE_ID,UPDATE_DATE) VALUES (1,1,1,CURRENT DATE);
INSERT INTO CSM_ROLE_PRIVILEGE (ROLE_PRIVILEGE_ID,ROLE_ID,PRIVILEGE_ID,UPDATE_DATE) VALUES (2,2,1,CURRENT DATE);


/* Table Objects for table csm_user*/



DROP TABLE  CSM_USER;

CREATE TABLE CSM_USER (
  USER_ID DECIMAL(31) NOT NULL ,
  LOGIN_NAME varchar(100) NOT NULL default '',
  FIRST_NAME varchar(100) NOT NULL default '',
  LAST_NAME varchar(100) NOT NULL default '',
  ORGANIZATION varchar(100) default NULL,
  DEPARTMENT varchar(100) default NULL,
  TITLE varchar(100) default NULL,
  PHONE_NUMBER varchar(15) default NULL,
  PASSWORD varchar(100) default NULL,
  EMAIL_ID varchar(100) default NULL,
  START_DATE date default NULL,
  END_DATE date default NULL,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (USER_ID),
  CONSTRAINT UQ_LOGIN_NAME UNIQUE (LOGIN_NAME)
) ;


/* Dumping data for table csm_user*/



INSERT INTO CSM_USER (USER_ID,LOGIN_NAME,FIRST_NAME,LAST_NAME,ORGANIZATION,DEPARTMENT,TITLE,PHONE_NUMBER,PASSWORD,EMAIL_ID,START_DATE,END_DATE,UPDATE_DATE) VALUES (1,'admin@admin.com','Admin','Admin',NULL,NULL,NULL,NULL,'6c416f576765696c6e63316f326d3365','admin@admin.com','2005-08-30',NULL,'2005-08-30');


/* Table Objects for table csm_user_group*/



DROP TABLE  CSM_USER_GROUP;

CREATE TABLE CSM_USER_GROUP (
  USER_GROUP_ID DECIMAL(31) NOT NULL ,
  USER_ID DECIMAL(31) NOT NULL default 0,
  GROUP_ID DECIMAL(31) NOT NULL default 0,
  PRIMARY KEY (USER_GROUP_ID)
) ;
CREATE INDEX IDX_USER_ID ON CSM_USER_GROUP(USER_ID);
CREATE INDEX IDX_GROUP_ID ON CSM_USER_GROUP(GROUP_ID);


/* Dumping data for table csm_user_group*/



INSERT INTO CSM_USER_GROUP (USER_GROUP_ID,USER_ID,GROUP_ID) VALUES (1,1,1);


/* Table Objects for table csm_user_group_role_pg*/



DROP TABLE  CSM_USER_GROUP_ROLE_PG;

CREATE TABLE CSM_USER_GROUP_ROLE_PG (
  USER_GROUP_ROLE_PG_ID DECIMAL(31) NOT NULL ,
  USER_ID DECIMAL(31) default NULL,
  GROUP_ID DECIMAL(31) default NULL,
  ROLE_ID DECIMAL(31) NOT NULL default 0,
  PROTECTION_GROUP_ID DECIMAL(31) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (USER_GROUP_ROLE_PG_ID)
) ;
CREATE INDEX IDX_GROUP_ID ON CSM_USER_GROUP_ROLE_PG(GROUP_ID);
CREATE INDEX IDX_ROLE_ID ON CSM_USER_GROUP_ROLE_PG(ROLE_ID);
CREATE INDEX IDX_PROTECTION_GROUP_ID ON CSM_USER_GROUP_ROLE_PG(PROTECTION_GROUP_ID);
CREATE INDEX IDX_USER_ID ON CSM_USER_GROUP_ROLE_PG(USER_ID);


/* Dumping data for table csm_user_group_role_pg*/



/* Table Objects for table csm_user_pe*/



DROP TABLE  CSM_USER_PE;

CREATE TABLE CSM_USER_PE (
  USER_PROTECTION_ELEMENT_ID DECIMAL(31) NOT NULL ,
  PROTECTION_ELEMENT_ID DECIMAL(31) NOT NULL default 0,
  USER_ID DECIMAL(31) NOT NULL default 0,
  UPDATE_DATE date NOT NULL default CURRENT DATE,
  PRIMARY KEY  (USER_PROTECTION_ELEMENT_ID),
  CONSTRAINT UQ_USER_PROTECTION_ELEMENT_PROTECTION_ELEMENT_ID UNIQUE (USER_ID,PROTECTION_ELEMENT_ID)
) ;
CREATE INDEX IDX_USER_ID ON CSM_USER_PE(USER_ID);
CREATE INDEX IDX_PROTECTION_ELEMENT_ID ON CSM_USER_PE(PROTECTION_ELEMENT_ID);

/* Dumping data for table csm_user_pe*/



/*  CONSTRAINTs for table csm_group*/



ALTER TABLE CSM_GROUP
  ADD CONSTRAINT (APPLICATION_ID) REFERENCES `CSM_APPLICATION` (APPLICATION_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_pg_pe*/



ALTER TABLE CSM_PG_PE
  ADD CONSTRAINT (PROTECTION_ELEMENT_ID) REFERENCES CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (PROTECTION_GROUP_ID) REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_protection_element*/



ALTER TABLE CSM_PROTECTION_ELEMENT
  ADD CONSTRAINT (APPLICATION_ID) REFERENCES `CSM_APPLICATION` (APPLICATION_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_protection_group*/



ALTER TABLE CSM_PROTECTION_GROUP
  ADD CONSTRAINT (APPLICATION_ID) REFERENCES `CSM_APPLICATION` (APPLICATION_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (PARENT_PROTECTION_GROUP_ID) REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID);



/*  CONSTRAINTs for table csm_role*/



ALTER TABLE CSM_ROLE
  ADD CONSTRAINT (APPLICATION_ID) REFERENCES `CSM_APPLICATION` (APPLICATION_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_role_privilege */



ALTER TABLE CSM_ROLE_PRIVILEGE
  ADD CONSTRAINT (PRIVILEGE_ID) REFERENCES CSM_PRIVILEGE (PRIVILEGE_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (ROLE_ID) REFERENCES CSM_ROLE (ROLE_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_user_group */



ALTER TABLE CSM_USER_GROUP
  ADD CONSTRAINT (GROUP_ID) REFERENCES CSM_GROUP (GROUP_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (USER_ID) REFERENCES CSM_USER (USER_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_user_group_role_pg */



ALTER TABLE CSM_USER_GROUP_ROLE_PG
  ADD CONSTRAINT (GROUP_ID) REFERENCES CSM_GROUP (GROUP_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (PROTECTION_GROUP_ID) REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (ROLE_ID) REFERENCES CSM_ROLE (ROLE_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (USER_ID) REFERENCES CSM_USER (USER_ID) ON DELETE CASCADE;



/*  CONSTRAINTs for table csm_user_pe */



ALTER TABLE CSM_USER_PE
  ADD CONSTRAINT (USER_ID) REFERENCES CSM_USER (USER_ID) ON DELETE CASCADE,
  ADD CONSTRAINT (PROTECTION_ELEMENT_ID) REFERENCES CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID) ON DELETE CASCADE;

